### PR TITLE
Importer - 5 - tripal importer make preparer compatible

### PR DESCRIPTION
**Pull request by risharde**
This was work done to the chado preparer that is considered necessary for Tripal Importers to function properly

### CODE REVIEW

**Comment by laceysanderson** [comment]
@risharde I'm holding off on reviewing this until the tests are passing.

**Comment by risharde** [comment]
@laceysanderson might be a dumb question, could you advise me on whether this is something on your side or my side, just want to make sure I'm not dropping the ball too much! Thanks much!!

**Comment by risharde** [comment]
@laceysanderson I'm still a bit confused by the error I am seeing with this and so I cannot resolve this at the moment. I cannot understand why the cv table would not be available during this preparation. Isn't the CV table part of the core chado schema? I need your help on this if you have the time. Please let me know, thanks!

**Comment by dsenalik** [comment]
Ha, that looks vaguely familiar. Look at this issue https://github.com/tripal/tripal/issues/1237 could it be related to this?

**Comment by laceysanderson** [comment]
Hi @risharde, it's like I commented in the cofest. The `cv` table is there but it's in the `testchado` schema. Your old code in the `tripal_feature_install()` and sub-methods is not compatible with differently named schemas and assumes the `cv` table is in a schema named `chado` which doesn't exist on purpose in the automated testing environment to ensure everything supports multiple schema. 

This should be your first thought and thing to check whenever a table cannot be found in Tripal 4.

For example, you are using the `tripal_insert_cv()` API function. When you look at the code for that you actually find out that is deprecated:
```php
/**
 * Adds a controlled vocabulary to the CV table of Chado.
 *
 * @param $name
 *   The name of the controlled vocabulary. These are typically all lower case
 *   with no special characters other than an undrescore (for spaces).
 * @param $comment
 *   A description or definition of the vocabulary.
 *
 * @return
 *   An object populated with fields from the newly added database.
 *
 * @ingroup tripal_chado_module_DEPRECATED_api
 */
function tripal_insert_cv($name, $definition) {
  return chado_insert_cv($name, $definition);
}
```

So you will want to change it to `chado_insert_cv()`. When you look at that function you find it now supports multiple schema through the `$schema_name` parameter with a default of `chado`:
```php
/**
 * Adds a controlled vocabulary to the CV table of Chado.
 *
 * @param $name
 *   The name of the controlled vocabulary. These are typically all lower case
 *   with no special characters other than an undrescore (for spaces).
 * @param $comment
 *   A description or definition of the vocabulary.
 * @param $options
 *   No options currently supported. For consistency.
 * @param $schema_name
 *   The name of the chado schema the records reside in.
 *
 * @return
 *   An object populated with fields from the newly added database.
 *
 * @ingroup tripal_chado_cv_api
 */
function chado_insert_cv($name, $definition, $options = [], $schema_name = 'chado') {
```

Since you didn't provide that parameter as you were using the deprecated function, the prepare task failed on github tests because it was looking for the table in the wrong schema.

To fix this you need to use the schema name passed into the task and now saved in `$this->outputSchemas[0];` and pass that to the `chado_insert_cv()` function.

This kind of update will need to be done for all of the functions you use in your new section of the prepare code.

I hope that helped!

**Comment by risharde** [comment]
@laceysanderson thanks so much, definitely helps, began trying to convert the deprecated functions out! Will keep you posted when I *think* I'm finished

**Comment by risharde** [comment]
@laceysanderson I think I've removed the deprecated functions but the tests still fail. When I click on details, the error doesn't actually point to the functions but I'm not sure so if you get a chance, could you double check the errors and let me know?

**Comment by risharde** [comment]
Close in favour of preparer_requirements branch which should go directly into core

**Comment by risharde** [comment]
Thanks Lacey! This makes sense and I forgot you mentioned this previously
(distracted with GFF3 loader's latest code - which works now!). I'll review
this in much more detail when I work on this soon!

Thanks again!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request closed without merging**
