### PR TITLE
Step 12 - Tripal Importer - Custom Tables UI and api changes

### PR DESCRIPTION
**Pull request by risharde**
A lot of code added to make Custom Tables administration. Custom edit fields for editing links. Custom view code for creating the actual views etc.

@laceysanderson

### CODE REVIEW

**Comment by spficklin** [comment]
So, I made some fixes to this branch
1.  Updated it to match Drupal coding standards.  I change the `tripal_chado.custom_tables.api.inc` file to have 2 spaces for indentation and to replace the older `array()` functions calls rather than the newer brackets form `[]`.
2. I fixed a bug with the `->insert()` function in the `chado_edit_custom_table` function
3. Renamed the router paths to be  more specific to the action that was occuring
4. Updated the view to use the new paths.  (you'll need to delete the view and rebuild the cache to pick up the changes).
5. Fixed some comments

However, the editing functionality is not working. I tried editing a table to change one of it's columns and it did not update the array for the table nor did it change the table in the database.

**Review by spficklin — CHANGES_REQUESTED** [review]
See comments above for requested fixes.

**Comment by risharde** [comment]
@laceysanderson I made the rowCount changes to the importer reviewed branch but I didn't create a PR for this branch since I think we're compiling everything in there before we do the PR to merge to main right?

**Comment by spficklin** [comment]
@risharde was that last comment meant for a different PR?

**Comment by risharde** [comment]
@spficklin it was, sorry, removed!

**Comment by risharde** [comment]
@spficklin I'm having problems with a few things in this branch now that I'm testing it. I'm not sure if they are related to any changes you made but let me know if it could be. 

1. The menu links for Chado Custom tables is no longer showing up.
2. Deleting the view according to your point #4 and performing a drush cr does not recreate the view

Not sure how to proceed but I'll try to see how I can get these going again. I know you were working it and it was working for you so I'm not sure at which point there might be an automation issue with the creation of the view

**Comment by risharde** [comment]
@laceysanderson I need your elite ninja Drupal skills here if you can help me plot a way forward (critical mind blocker at the moment). I thought at first that this would be a simple fix but I don't think it is (?). The Custom Tables UI uses the following function to create a custom table:

chado_create_custom_table (ref link below)
https://github.com/tripal/t4d8/blob/c3f560978542ed05cf7f5979b6b7341a8b64c58d/tripal_chado/src/api/tripal_chado.custom_tables.api.inc#L113

It uses $connection->schema()->createTable($chado_dot . $table, $schema); to create the table based on the schema which is the associated array schema for the table. THIS WAS WORKING IN 8 BUT NOW, THIS IS CREATING LITERALLY TABLES LIKE 'chado.drupal_test' in the PUBLIC SCHEMA

Any ideas on what the best direction would be? I feel like trying to recreate code to translate a schema array into SQL and using it in chado_query might not necessarily be the way forward or is it? Maybe I'm missing something obvious that could be done.

**Comment by risharde** [comment]
New code for Tripal Custom tables uses a new method to work on Chado tables. You are required to add the following to settings.php in order for this to work. Username and Password would need to be set correctly. The code below is just an example.

$databases['default']['default'] = array (
  'database' => 'drupal',
  'username' => 'drupal',
  'password' => 'drupal',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '5432',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\pgsql',
  'driver' => 'pgsql',
);
$databases['chado']['default'] = array (
  'database' => 'drupal',
  'username' => 'drupal',
  'password' => 'drupal',
  'prefix' => 'chado.',
  'host' => 'localhost',
  'port' => '5432',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\pgsql',
  'driver' => 'pgsql',
);

**Comment by risharde** [comment]
@spficklin up for review if you have that chance to check. Editing chado custom tables also works now.

**Comment by spficklin** [comment]
@laceysanderson and @guignonv what do you think of requiring that a connection array to the Chado database be specified in the Drupal `settings.php` file?  This was the simplest way we could make creating of custom tables in Chado work. 

**Pros**:  
1. We don't need to redo any Drupal classes to make custom tables work, and it may offer a solution to explore a fix for the problem we had with switching schema's during unit testing.  
2. It would make more of the Drupal database functions accessible for use on Chado tables rather than some of our Chado API functions. So we may be able to reduce some code by calling Drupal functions. 
3. It may simplify the multi-chado installations? @guignonv would adding all of the Chado installations in the `settings.php` file help?

**Cons**: 

1. It requires an additional installation step to add the Chado settings to the `settings.php` file.

**Comment by guignonv** [comment]
Quick answer that I will expand later: I don't think it should be a requirement. We should discuss that (maybe today?). The new Chado API (BioDB) should allow you to manage custom tables without touching files (settings.php). However, that same API supports additional databases specified in the settings.php as well which would include Chado databases. It would provide one advantage I see: security, as you could configure 2 distinct Postgresql connections with specific roles that have restricted access to each part of the database(s).

**Comment by guignonv** [comment]
To provide a more complete answer, you should merge branch tripal-biodb:
https://github.com/tripal/t4d8/tree/tripal-biodb

It will update Chado API so you can work with Chado properly. With that branch (which shoule be merged to Drupal core soon @laceysanderson ?), you can address the schema selection problem.

You have at least 2 possibilities:
1) if you create tables using the Drupal database API methods, create a new Chado connection and use that connection to create tables.
2) if you prefer to use SQL queries, once again, create a new Chado connection and just do minor changes in your query: while, for Drupal tables, you would use the curly braces notation, for Chado tables, you will also use that notation with a table brefix '1:'. For instance "SELECT * FROM {1:feature};".

Some code example:
```
// Create a Chado connection
$biodb = \Drupal::service('tripal_chado.database');

$table_shema = [
  "description" => "Some custom table.",
  "fields" => [
    "custable_id" => [
      "type" => "serial",
      "not null" => true,
      "pgsql_type" => "bigserial",
      "size" => "big",
    ],
    "dbxref_id" => [
      "type" => "int",
      "not null" => false,
      "pgsql_type" => "bigint",
      "size" => "big",
    ],
    "name" => [
      "type" => "varchar",
      "not null" => false,
      "pgsql_type" => "character varying",
      "length" => 255,
    ],
    "uniquename" => [
      "type" => "text",
      "not null" => true,
      "pgsql_type" => "text",
    ],
    "description" => [
      "type" => "text",
      "not null" => false,
      "pgsql_type" => "text",
    ],
    "type_id" => [
      "type" => "int",
      "not null" => true,
      "pgsql_type" => "bigint",
      "size" => "big",
    ],
  ],
  "primary key" => [
    "custable_id",
  ],
  "unique keys" => [
    "custable_c1" => [
      "uniquename",
      "type_id",
    ],
  ],
  "foreign keys" => [
    "custable_dbxref_id_fkey" => [
      "table" => "dbxref",
      "columns" => [
        "dbxref_id" => "dbxref_id",
      ],
    ],
    "custable_type_id_fkey" => [
      "table" => "cvterm",
      "columns" => [
        "type_id" => "cvterm_id",
      ],
    ],
  ],
];


// Create a new table in Chado schema, solution 1:
$biodb->schema()->createTable('custable', $table_shema);

// Then if you want to drop the table:
$biodb->schema()->dropTable('custable');

// Create a new table in Chado schema, solution 2:
$sql_create_table = "
  CREATE TABLE {1:custable} (
    custable_id bigserial NOT NULL,
    dbxref_id bigint NULL,
    name character varying NULL,
    uniquename text NOT NULL,
    description text NULL,
    type_id bigint NOT NULL,
    CONSTRAINT custable____pkey PRIMARY KEY (custable_id),
    CONSTRAINT custable__custable_c1__key UNIQUE (uniquename, type_id)
  );
";
$sql_comment_table = "
  COMMENT ON TABLE {1:custable} IS 'Some custom table.';
";
$query = $biodb->query($sql_create_table);
$query = $biodb->query($sql_comment_table);

// Note: to get table definition in Drupal Schema API format:
$table_schema = $biodb->schema()->getTableDef('custable', ['source' => 'database', 'format' => 'drupal']);
// ...to get table definition in SQL format:
$table_schema = $biodb->schema()->getTableDef('custable', ['source' => 'database', 'format' => 'sql']);
```

Note: Chado API (BioDB API) is based on Drupal DB API so you can use the exact same methods for [connections](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Database%21Connection.php/class/Connection/9.3.x) and [schemas](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Database%21Schema.php/class/Schema/9.3.x) with some more features documented [there](https://tripal4.readthedocs.io/en/latest/design/pending/biodb/design.html#biological-database-api).


Important note: using this API as shown above will keep you compatible with both multiple Chado aware and non-aware (future) extensions. Indeed, those instructions will work on the default Chado schema (\Drupal::service('tripal_chado.database')) which can be altered by extensions. So, for instance, I want to work on a secondary Chado schema 'my_chado', I could have an extension that would activate it on demand and then I could use the regular interface to created custom tables and it will go there (in 'my_chado') while, from the perspective of the custom table manager, no code needed to be changed.

If "you" need to know, from the Drupal side, on which schema you are working on (ie. you want to store some extra info outside Chado about custom tables), you can get it with: `$biodb->getSchemaName();`. The returned string will be the schema name and you can store it somewhere.

**Comment by laceysanderson** [comment]
Note: As mentioned in the Tripal BioDB roadmap issue and in our weekly meeting, you should merge the `tripal-biodb` branch into this branch for further development + testing. You do not need to wait until `tripal-biodb` is merged into `9.x-4.x` as the changes should be minimal.

**Comment by risharde** [comment]
@laceysanderson @spficklin 
Merged biodb into this branch
Upgraded the tripal_chado.custom_tables.api.inc to use BioDB
Tested the UI to ensure a custom table gets created, edited (by adding an addition field via the table schema array) and delete a table.

**Comment by laceysanderson** [comment]
Hey @risharde, please resolve the automated test errors. These were an issue before merging in tripal-biodb. When creating tests there should only be a single class in each test file and it should match the name of the file. You're running issues since you added a ChadoQueryAPITest class inside your ChadoCustomTablesAPITest.php rather than re-using the existing version of that class and adding methods.


Screen Shot 2022-02-22 at 3 38 42 PM
Screen Shot 2022-02-22 at 3 38 32 PM

**Comment by risharde** [comment]
@laceysanderson not sure exactly what I did but it says it deleted this branch (I guess renaming also means deleted - anyways, the new branch is here: https://github.com/tripal/t4d8/tree/tv4g4-4-tripal_importer_chado_custom_tables where I resolved the class name). Sorry for the delay on this.

**Pull request closed without merging**
