### PR TITLE
Step 10 - Tripal Importer - ChadoInstaller specific changes

### PR DESCRIPTION
**Pull request by risharde**
In order for the Tripal loaders to function correctly, they need some required tables. These tables / schema have been added to the chado installer so they get created when chado gets installed.

@laceysanderson

### CODE REVIEW

**Review by laceysanderson — CHANGES_REQUESTED** [review]
And this is exactly why we split it out into multiple PRs since this would be missed in the original big one.

This is the wrong place for this code. We don't want to add it to the chado installed but instead it should be part of the prepare step.

[Here is the prepare in Tripal 3](https://github.com/tripal/tripal/blob/4f19a230b82f8ed3c949349b7ebd1137bdfb74bb/tripal_chado/includes/setup/tripal_chado.setup.inc#L185) and you can see it adds these tables.

And [here is the prepare service in Tripal 4](https://github.com/tripal/t4d8/blob/9.x-4.x/tripal_chado/src/Services/chadoPreparer.php) where you will want to move this code :-)

**Comment by risharde** [comment]
@laceysanderson I have a question - is it safe to assume the prepare service gets run when chado is called to be installed? Sorry if this is a dumb question - just making sure

**Comment by laceysanderson** [comment]
Prepare will not get called at the same time as chado install but admin will be told that they have to prepare their default chado before continuing. You will want to do a quick check that the table is there before using it the first time and if not tell admin to prepare their database.

**Comment by risharde** [comment]
@laceysanderson I've tried my best to transfer the functions to the chadoPreparer class as advised. Because I'm working blindly on an incomplete branch, I didn't try to change code in fear of adding errors to what was previously working. Maybe we can add this modification after we've merged into tripalImportedReviewed when it has enough code to become functional?

**Comment by risharde** [comment]
I will try to reconstitute the pending PRs with the ImporterReviewed branch to see if everything works as planned but maybe after a few more PRs get merged in at your convenience

**Review by laceysanderson — COMMENTED** [review]
The changes to the prepare class look good :-) 👍 

However, there are still some changes to the chadoInstaller... I do not believe there should be any changes to this file for this PR. The feature-related stuff should also move into the prepare class.

**Comment by risharde** [comment]
@laceysanderson I've made the changes you requested, moving over the feature functions to chadoPrepare and restoring chadoInstaller to original from 9.x-4.x branch

**Review by laceysanderson — APPROVED** [review]
Changes look good and the tests were passing. Just waiting for the update from master to pass and then we can merge!

**Pull request merged**
