### PR TITLE
Correct typos and change cases in dev guide docs

### PR DESCRIPTION
**Pull request by michizhou**
Resolved typos in the development guide documentation pages for better readability. Also changed cases for references to "Tripal" and "Chado" to make them more consistent with similar references in the documentation.

### CODE REVIEW

**Review by laceysanderson — APPROVED** [review]
Thank you for the contributions!

**Comment by ghost** [comment]
Last week I was using installation instructions like:
Native Docker — Tripal 4.x 8.x-4.x documentation - Read the Docstripal4.readthedocs.io › latest › install › docker
Pull the docker image onto your computer: docker pull laceysanderson/tripal4dev:tripal4-d8.8.x. Clone a local copy of tripal 4: https://github.com/tripal/t4d8.git.

Today, the same page no longer has instructions for laceysanderson image. I'm confused. I'm new so maybe my confusion is the only problem.

**Comment by laceysanderson** [comment]
Hello @pst024, Sorry for the confusion! I've updated the guide as my original laceysanderson image has become the official tripaldocker image. The older image will no longer be maintained. This is now the analogous documentation page: https://tripal4.readthedocs.io/en/latest/install/docker.html 

I suggest switching to TripalDocker as there are some important improvements: 
 - global access to drush/composer/drupal console
 - updated Drupal/Tripal version
 - Access of the site at localhost:9000 (better apache config). 

That said, the instructions for the older docker are here: https://github.com/tripal/t4d8/blob/b24ce790f11a1ea37be922fec2b397325d7d6177/docs/install/docker.rst 

Is the updated documentation harder to follow?

Also, if you run into issues/suggestions with the new docker just let me know through an issue on here and I'll get them fixed ASAP.

**Comment by ghost** [comment]
Thanks so much for your support and explanation. And for how quickly you
respond! I'm sure the new documentation will be helpful. I'm glad to know
how to proceed and that I wasn't crazy, LOL.

Pam St, Michel

**Comment by ghost** [comment]
Hi Lacey-Anne,

I am working at the University of Minnesota. The websites at the UMN are
hosted by Acquai and I've been using a customized Acquia Dev Desktop that
allows you to install, test, and build Drupal sites locally on your Mac or
Windows PC.

I want to try to run Tripal on the Mariadb on my local virtual machine
using the environment setup by ddev for Drupal 8 localhost development. Do
you think I'll have any luck trying this? I think I'll need to clone your
t4d8 instead of using your docker images.

Thanks,

Pam St. Michel

**Comment by laceysanderson** [comment]
I don't know if you will unfortunately. Chado (the database biological database data is stored in) is very PostgreSQL specific and as a result, Tripal may have leaned that way. Chado is focused on PostgreSQL due to data integrity concerns as well as simple history. If you give it a try, let me know how it goes. We may be able to work with you on the Tripal side of things though Chado is developed separately. That said, Tripal 4 is focusing on making it easy to store data for fields in different databases so... *shrugs* If possible, I would suggest using PostgreSQL.

**Comment by ghost** [comment]
Thanks for the reply. I need to mull this over. But I appreciate your
insights. I'll let you know my plans.

Pam

**Pull request merged**
