### PR TITLE
Tripal Id Space and Vocabulary Plugins

### PR DESCRIPTION
**Pull request by 4ctrl-alt-del**
The tripal fields branch is ready to be merged to the main branch with the new and fully functional id space and vocabulary plugin system. This includes working chado plugins implemented by @spficklin.

### CODE REVIEW

**Comment by spficklin** [comment]
To add to this.  I don't think we need anything more in terms of testing.  There are, almost 200 assertions in the functional tests for this work so unless @laceysanderson thinks we need another code review I would suggest this is ready for merging.

**Comment by spficklin** [comment]
Although before we commit, we should figure out why GitHub is showing that "Water Coyote" has contributed a lot of code rather than @4ctrl-alt-del

**Comment by 4ctrl-alt-del** [comment]
I resolved the contribution error with github, they said it was some sort of database error. It should now show "Josh B".

**Comment by spficklin** [comment]
I just had a quick conversation with @laceysanderson on Slack about this PR.  I need it for doing tests with the ChadoStorage class and she agreed it looks good to merge. So merging.

**Pull request merged**
