### PR TITLE
Step 9 - Tripal Importer - Dynamic Menu for Tripal Loaders

### PR DESCRIPTION
**Pull request by risharde**
This is the code that adds each Tripal Loader as a link in the admin menu

### CODE REVIEW

**Review by laceysanderson — APPROVED** [review]
Code review ✅

**Comment by laceysanderson** [comment]
Tests are failing because it doesn't have the API functions it needs :-( which is a product of how the PRs are split up. Sicne the API parts were already merged into our reviewed branch. I'm going to merge that into here so these tests have what they need :-) Since `tv4-tripalImporterReviewed` is our base branch this is the same process as if we were updating a typical PR with the most recent version of 9.x-4.x

**Comment by laceysanderson** [comment]
Ok, now I've confirmed there is a problem with this code based on this error in the tests:
```
 Error: Call to undefined function Drupal\tripal\Routing\tripal_get_importers() in Drupal\tripal\Routing\TripalRoutes->dataLoaders() (line 20 of /var/www/drupal8/web/modules/contrib/tripal/tripal/src/Routing/TripalRoutes.php).
```

I confirmed that the tripal_get_importers() function is in this branch as shown here:
```
 grep -nR "tripal_get_importers" *
tripal/src/Plugin/Derivative/TripalImporterLink.php:46:    $importers = tripal_get_importers();
tripal/src/api/tripal.importer.api.php:85:function tripal_get_importers() {
tripal/src/Routing/TripalRoutes.php:20:    $importers = tripal_get_importers();
```

Thus the problem is related to namespaces which you can see because the error message indicates that it can't find `Drupal\tripal\Routing\tripal_get_importers()`. @risharde can you look into fixing this? You should be able to test using this branch by running the tests locally

**Review by laceysanderson — CHANGES_REQUESTED** [review]
Tests need to pass for this to be merged

**Comment by risharde** [comment]
hmmm I'm a little lost on this one to be honest but maybe I'm just overloaded and need to take a break - cannot understand why this would look for that specific function in Drupal\tripal\Routing\ @laceysanderson

**Comment by laceysanderson** [comment]
It is getting to be the end of the year and I think we could all use a break 🤗 

It's looking for the function there because that's the namespace for that file. You should be able to fix it by telling PHP/Drupal that this function is in the core namespace using `/tripal_get_importers()` I think.

**Comment by risharde** [comment]
Hi @laceysanderson, so I adjusted the tripal_get_importers to \tipal_get_importers() - hopefully this works

**Comment by risharde** [comment]
I just realized on my side, the issue still shows called to undefinited function - I think perhaps this might be because it may not have been imported via the actual tripal.module file. I went ahead and added the require_once. I think previously I wanted to do all the require_once calls in a seperate PR but I guess that won't happen if we're testing - that's the counter argument for these splits

**Comment by laceysanderson** [comment]
Nice, now we're getting somewhere! This last failure is due to your permission change for admin/tripal/loaders. You do not want to use a specific permission for that URL to [keep consistent with Tripal 3](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/tripal.module#L355-L364). The loader-specific permissions are good 👍  but use administer Tripal for admin/tripal/loaders.

**Comment by risharde** [comment]
@laceysanderson sorry for the delay on this, adjusted the permission for the main path to administer tripal as requested

**Review by laceysanderson — APPROVED** [review]
Tests now pass! Just waiting on merge conflict resolving commit to pass tests

**Pull request merged**
