### PR TITLE
Fix for issue #218

### PR DESCRIPTION
**Pull request by spficklin**
This PR provides a fix for issue #218.   It just checks to see if a prefix has already been applied to a table and if so does not allow it to be applied again by removing the curly braces from around the table name. 
 
This should prevent the problem that occurs in when running an update and the prefixTables function is called twice leading to two prefixes being added.

I'm not sure how to suggest testing this.  There are no functional tests for updates of the TripalDBX and I'm writing some for the IDSpace and Vocabulary classes and that's how I found this problem but those tests are on another branch.

### CODE REVIEW

**Comment by spficklin** [comment]
I should add. That when I put these fixes into my branch `tv4g1-129-TripalFields-spf` I am able to complete the tests... no problem.

**Review by laceysanderson — APPROVED** [review]
This is a small, easy to understand update that doesn't break any existing functionality. Since we are in active development I say we merge without additional testing and if anything turns up in the future we'll fix it then. That said, I don't see any problems arising from this based on the carefulness of the regex.

**Comment by spficklin** [comment]
Yeah, from this point forward we should be writing lots of code that will fully stress test the Tripal DBX so any other problems should work themselves out if this code misses something.

**Comment by laceysanderson** [comment]
Merged! 🎉 Nice fix!

**Pull request merged**
