### PR TITLE
Jobs Managment

### PR DESCRIPTION
**Pull request by spficklin**
Issue  #3

This PR fully supports jobs management.  The following contributions are in this PR:

1.  The Jobs API functions are all now Drupal 8/9 compatible.
2.  The `TripalJob` class is now Drupal 8/9 compatible.
3.  The Jobs View is fully redone (and redesigned) and is Drupal 8/9 compatible.  This resulted in an updated `tripal.views.inc` file to describe tables to Views and a new `config/install/views.view.tripal_jobs.yml` file which replaces the old default views file from Drupal 7. 
4.  The `trp-run-jobs` and `trp-rerun-job` drush commands are working and compatible with **Drush 9**.  If you're not using Drush 9 you will need to upgrade (Note: Drush 10 doesn't work).  This resulted in a new `drush.services.yml` file being added and a new `src/Commands/TripalCommands` file being added.
5. I updated the `ChadoInstallForm` class to use the updated Jobs API functions and it is now possible to install Chado using the Jobs system and Drush.
6.  There is a new `TripalLogger` service class. This class mimics exactly the Drupal logger functions but has all of the functionality of our `tripal_report_error` function.  This logger can be used anywhere in Tripal but it also supports logging to Jobs which is why I created it.  I also changed the `bulkPgSchemaInstaller` to use this new logger.  
7.  I created an `api/tripal.deprecated.api.php` file for moving functions that are deprecated.  I moved the `tripal_report_error` ,  `tripal_log` and `tripal_get_job` functions there. We can move other API functions there as we replacement them with objects.
8. Also, I added a new page to the developer docs with some useful tips for upgrading modules.  These are things that I found along the way that I thought would be useful for others as they start upgrading their modules.
9.  CSS entries for jobs have been moved into a new `css/tripal.jobs.css` file to keep unnecessary CSS entries from being used all over. 
10.  I created a new `TripaljobsController` to respond to routes that were specific to Jobs.  Otherwise, the `TripalController` would eventually become overwhelmingly huge as we implement everything.
11. For the Job routing I removed the URLs that I don't think Tripal actually uses but were left over from some earlier versions.

What's missing:
I have not yet done functional testing.  But, I wanted to get this merged in so others can take advantage of Jobs and Logging.

### CODE REVIEW

**Comment by laceysanderson** [comment]
I'm excited for all this functionality! However, this cannot be merged until the tests pass thanks to branch protections... It looks like all the tests are failing with the same error:

> Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for views.view.tripal_jobs with the following errors: views.view.tripal_jobs:display.default.display_options.fields.priority.set_precision missing schema, views.view.tripal_jobs:display.default.display_options.fields.priority.precision missing schema, views.view.tripal_jobs:display.default.display_options.fields.priority.decimal missing schema, views.view.tripal_jobs:display.default.display_options.fields.priority.separator missing schema, views.view.tripal_jobs:display.default.display_options.fields.priority.format_plural missing schema, views.view.tripal_jobs:display.default.display_options.fields.priority.format_plural_string missing schema, views.view.tripal_jobs:display.default.display_options.fields.priority.prefix missing schema, views.view.tripal_jobs:display.default.display_options.fields.priority.suffix missing schema

**Comment by spficklin** [comment]
Hmmm.... I'll see if I can get those fixed tonight..

**Comment by laceysanderson** [comment]
👍 I'm running through a functional test right now and it installed my chado as advertised :-)

**Comment by laceysanderson** [comment]
So I receive an "The website encountered an unexpected error. Please try again later." on the jobs listing page. 
This was the reported message:
Screen Shot 2020-10-27 at 9 48 16 PM

Based on the reported message it seems the tripal_jobs view is not loaded automatically. I confirmed this by going to the views listing -it wasn't there 😕 I rebuilt the cache repeatedly but no luck 😞 

I was able to confirm the logger worked perfectly though by going to the job view page through the URL 👍 I like how it follows the new drupal logger!

**Comment by spficklin** [comment]
Oh right, that makes sense. The view only gets installed when Tripal is first installed.  The reason is that the .yml file for the view goes in the `config/install` directory.  That's where Views wants to find it, and clearing the cache won't enable it.   Hmmm.... I'm not sure how to fix this without a reinstall of the module.  I need to dig deeper.

**Comment by spficklin** [comment]
Hi @laceysanderson would you mind pulling the branch again, clear the cache and see if the view is now there?  I added a tripal_rebuild hook that looks to see if the view is missing and if it is it adds it.  I couldn't find any other way to make Views recognize the default view. It's definition is in the `config/install` directory.  So, this is my work around.   But the advantage is that if someone accidentally deletes the view and clears the cache it will come back.

**Review by laceysanderson — APPROVED** [review]
Yay 🎉 works like a charm now 😃 I like the redesign! Also, thanks for adding to the docs!

✅ Manual functional tests complete!
✅ Quick Code review also looks good

This PR is just waiting on fixing the tests and then it can be merged!

**Comment by laceysanderson** [comment]
Fixed the schema issues in the view and a couple other small things that snuck in! I then re-tested the functionality and this is now ready to merge!

**Pull request merged**
