### PR TITLE
Migrate File Forms to Drupal 8

### PR DESCRIPTION
**Pull request by almasaeed2010**
Issue #23 

Adds forms for Tripal's file quota management system.

### Testing
- Visit `/admin/tripal/files`
  - There should be 4 links, try to test all links
  - Note that in the `Users Quota` page, there is a link under `CUSTOM SETTINGS` to add quota to a specific user. Please test that as well.

### Notable Changes
- Optimized query to calculate total storage usage. It used to loop through all items to calculate the total. It now executes a single query to compute the sum of file sizes.
- We now use states instead of Drupal variables since those are removed from D8. 

### Notes
I couldn't figure out how to render links in a table. So, the edit and remove links under `CUSTOM SETTINGS` will not render correctly.

### CODE REVIEW

**Review by laceysanderson — COMMENTED** [review]
### Functional Testing:
 - Manage Usage page works perfectly -saves changes to form without error. ✅ 
 - User Quotas page (`admin/tripal/files/quota`) errors on submit. Specifically, when I change the "Default System-Wide Expiration Date" from 60 to 45 and then click the "Save" button I see `The website encountered an unexpected error. Please try again later.` When I look at the recent log messages this is the only one:
Firefox_Screenshot_2020-01-10T17-33-42 693Z
 - Add Custom User Quota forms works perfectly ✅ 
 - File Usage page is just as helpful as before 🙃 

### Automated Testing
All tests fail with the following message:
```
Drupal\Core\Config\Schema\SchemaIncompleteException: No schema for tripal.settings

/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Config/Development/ConfigSchemaChecker.php:88
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Config/Config.php:231
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:378
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:137
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php:75
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:288
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:469
/Users/laceysanderson/Sites/tripal4/web/core/tests/Drupal/Tests/BrowserTestBase.php:570
/Users/laceysanderson/Sites/tripal4/web/core/tests/Drupal/Tests/BrowserTestBase.php:398
```

**Comment by almasaeed2010** [comment]
@laceysanderson thanks for testing! I published a fix for the quota form but I am unable to run phpunit so I couldn't figure out what is causing the exception. [According to this](https://www.drupal.org/docs/8/api/configuration-api/configuration-schemametadata), this error would occur when the structure of a configuration file doesn't match its schema. Since I didn't change any configuration, I don't understand why the error would happen on this branch only? Any ideas?

**Comment by laceysanderson** [comment]
The form issue is fixed -thank you!

I'll look into the failing tests now.

**Comment by laceysanderson** [comment]
I've confirmed that `tripal/config/install/tripal.settings.yml` is what is causing the tests to fail. According to https://www.drupal.org/docs/8/creating-custom-modules/defining-and-using-your-own-configuration-in-drupal-8 use of that file requires an associated `config_object` type schema. I still have further to dig but it's supper time so I figured I'd get this down before I forget. Deleting the file causes the tests to pass but it is unclear what repercussions that may have as I haven't tested further.

**Comment by laceysanderson** [comment]
Further research has turned up that the tripal.settings.yml is part of using the Drupal::config api whereas the rest of the PR uses the Drupal::state API. When I was exploring these API's I came across the following:

> Simple configuration (Config API) — Settings that require synchronization between different environments, e.g. site name, slogan, user account settings, etc.

> Local configuration (State API) — Settings that are more transient or subject to change and which should not be synchronized between environments. e.g. the last cron run, the timestamp for statistics, last update time, etc.

This leads me to lean towards using the Drupal::config API for file quota configuration since this is more permanent. Furthermore, using the config API allows us to sync these settings between development and production environments. **What do you think @almasaeed2010** ?

**Comment by almasaeed2010** [comment]
At first I thought the configuration API was too cumbersome to implement and test for simple operations such as this one. After some further reading though I agree we should use the config files instead. I'll try to push new changes to this asap.

Thanks!

**Comment by almasaeed2010** [comment]
Changes made to use Config API instead of States.

Thanks!

**Review by laceysanderson — COMMENTED** [review]
Functional test: Works perfectly! ✅ 
Code review ✅ 
Automated Testing: still failing due to the `tripal.settings.php` file
```
Drupal\Tests\tripal\Functional\TripalTermEntityTest::testTripalTermEntity
Drupal\Core\Config\Schema\SchemaIncompleteException: No schema for tripal.settings

/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Config/Development/ConfigSchemaChecker.php:88
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php:111
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Config/Config.php:231
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:378
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Config/ConfigInstaller.php:137
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php:75
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Extension/ModuleInstaller.php:288
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php:83
/Users/laceysanderson/Sites/tripal4/web/core/lib/Drupal/Core/Test/FunctionalTestSetupTrait.php:469
/Users/laceysanderson/Sites/tripal4/web/core/tests/Drupal/Tests/BrowserTestBase.php:570
/Users/laceysanderson/Sites/tripal4/web/core/tests/Drupal/Tests/BrowserTestBase.php:398
```

**Review by laceysanderson — APPROVED** [review]
Aha! Found it: you just forgot to describe the config_object schema of the settings. That is done in an `config/schema/tripal.settings.schema.yml` file as follows:
```
tripal.settings:
  type: config_object
  label: Tripal Settings
  mapping:
    files:
      type: config_object
      mapping:
        max_size:
          type: integer
        quota:
          type: integer
        expiration:
          type: integer
```

I'm approving this PR and merging it and then I'll add the file :-) Thank you for the contribution @almasaeed2010!

**Comment by almasaeed2010** [comment]
Oh I did t know config files needed schemas. Sorry about that! I am glad it’s working now though!

Thanks.

**Pull request merged**
