### PR TITLE
Automatic Creation of Single Valued, String Chado Fields

### LINKED ISSUE #236: Implement ChadoStorage::insertValues()
The `ChadoStorage::insertValues()` needs to be implmeneted.  

I'm adding a separate issue for each function of the ChadoStorage class that needs implementing because they are quite involved and could probably be best reviewed with individual PRs.

### LINKED ISSUE #237: Implement ChadoStorage::updateValues()
The `ChadoStorage::updateValues()` needs to be implmeneted.  

I'm adding a separate issue for each function of the ChadoStorage class that needs implementing because they are quite involved and could probably be best reviewed with individual PRs.

### PR DESCRIPTION
**Pull request by spficklin**
## Issues Addressed
Issue tripal/t4d8#129
Issue tripal/t4d8#236 
Issue tripal/t4d8#237

Wait to review this until after the merge of PR tripal/t4d8#254 because this PR has that code in it and all of the changes in that PR are also showing up here.

## Description
This PR provides new functionality for field creation. It will automatically add all single-valued string fields to all content types during the Chado Prepare step.   The only exception is the 'Pub' content type. That one requires some special handling.  You can also create new entities for content types where the string fields are sufficient to meet the unique constraint (e.g. Organism).

This PR does not implement the `ChadoStorage::deleteValues()` function (issue tripal/tripal#1350) because there is not yet a distinction between an "Unpublish" and a "Delete" so I thought it would be best to not implement a delete until we had the buttons.  The  `ChadoStorage::findValues()` function is also not yet implemented (issue tripal/tripal#1351).

This PR also does not support integer fields, text fields or other database fields other than `character varying`.  I left a "@todo" comment in the code to finish those up.  But this PR is provided now so that everyone can have access to the new code. 

## How to Test
1. Uninstall Tripal, pull this branch and reinstall Tripal (or start from a brand new installation)
2. Install Chado
3. Prepare Chado. It should indicate all of the content types are created.  It's a bit slower creating content types now because it takes time to create all the fields.  
4. Go to Admin > Structure > Tripal Content Types. Pick any content type.  You will see the set of fields that have been added.  They should not appear in the 'Disabled' section but should be in the Content section.
5. Go to Content > Tripal Content > Add new Tripal Content and pick the Organism content type. Test creation and editing of the content type. 
6. Look in the Chado database in the organism table. A new record should exist in the organism table, and any changes you made should be there.
7. Return to the Admin > Structure > Tripal Content Types. You should be able to move the fields around on the manage display and manage form.  
8. Check out the field settings and the field storage settings. You should see the controlled vocabulary term that each field is assigned and the Chado table/column that the field maps to.

### CODE REVIEW

**Comment by spficklin** [comment]
Oh Dang. I just realized I broke the functional testing for the ChadoStorage because I had to rework it a bit for fields. So, the testing will fail.   I'll try to get back to fix it.

**Review by laceysanderson — DISMISSED** [review]
The tests should be fixed now :-)
Code review-wise: this PR is looking good. 
It works for single-value, single-property fields like those on the organism content type.

We will need to create more fields in order to ensure the ChadoStorage handles more complex fields like foreign key single- + multi-value fields. There is placeholders to test these two in the automated testing for when we get to implementing them :-)

**Comment by laceysanderson** [comment]
@risharde this one is also ready for you to review!

**Comment by spficklin** [comment]
I did a quick review of the changes @laceysanderson .  All looks good. Thanks for makin these fixes.

**Comment by spficklin** [comment]
I had a brief moment for coding, so I added in support for text fields. These are unlimited strings (e.g. organism.description).  So, now when you prepare Chado you should see the single-valued text fields appear as fields.

**Comment by spficklin** [comment]
In the process of working on a complex fields (obi__organism), I've discovered that we have a problem with this PR.  When setting the storage settings for a field, those are persistent between instances of the field.  So, if we use the same field for two different content types and link that field to a Chado table, it will always be linked to only one Chado table.  For example the `feature` table and `analysis` tables of Chado both have a `name` column.   A field of `rdfs:label` gets added to all content types for those tables.  But, in the end, that field always only points to one table.  I think the fix is to move the Chado associations into the field settings and out of the field storage settings.   I don't think this should stop this PR from getting merged in, we just need to fix this.  I'm working on a fix in the branch for the complex field.  

If there aren't any objections I think we move forward with a functional review by @risharde and merge if all is good and I'll make a new PR afterwards with the complex field and the fix for the problem I just described.

**Comment by risharde** [comment]
Overall working great @spficklin! 1 warning (hopefully minor) in the tripal prepare step - screenshot attached.
@laceysanderson 

[GOOD] Uninstall Tripal, pull this branch and reinstall Tripal (or start from a brand new installation)
[GOOD] Install Chado
[1 WARNING] Prepare Chado. It should indicate all of the content types are created. It's a bit slower creating content types now because it takes time to create all the fields.

@spficklin 
image

[GOOD] Go to Admin > Structure > Tripal Content Types. Pick any content type. You will see the set of fields that have been added. They should not appear in the 'Disabled' section but should be in the Content section.
[GOOD] Go to Content > Tripal Content > Add new Tripal Content and pick the Organism content type. Test creation and editing of the content type.
[GOOD] Look in the Chado database in the organism table. A new record should exist in the organism table, and any changes you made should be there.
[GOOD] Return to the Admin > Structure > Tripal Content Types. You should be able to move the fields around on the manage display and manage form.
[GOOD] Check out the field settings and the field storage settings. You should see the controlled vocabulary term that each field is assigned and the Chado table/column that the field maps to.

**Review by risharde — APPROVED** [review]
Functional tests worked so we're good to go here!

**Comment by spficklin** [comment]
Approved by @laceysanderson and @risharde ... all tests are passing but the Drupal 10 check which is breaking on Docker.  So, merging.

**Pull request merged**
