### PR TITLE
Html5 file upload

### PR DESCRIPTION
**Pull request by par12005**
# New Feature

Issue #22

## Description

 - Upgraded implementation of HTML5 File Upload Form Element.
 - Created Tripal file upload permissions.
 - Defined `tripal.upload` and `tripal.upload.chunk` routing information.
 - Added definitions for file and uploader JavaScript libraries.
    - There were some bugs in these that I was able to fix, particularly with the TripalUploader class during table updates and with a non-zero "cardinality" option.
 - Upgraded implementation of Tripal `files` and `notice` APIs.
    - Removed `tripal_format_bytes()` from Tripal `entities` API, since it exists in the `files` API.
 - Fixed implementation of `tripal_get_user_usage()` from the `quotas` API.
 - Added Tripal default JavaScript variables to every page, including `tripal_path` and `baseurl`. This is similar to the functionality of `tripal_init()` in Tripal 3.
 - Upgraded implementation of Tripal `upload` API, and added several functions that were previously in [`tripal/includes/tripal.upload.inc`](https://github.com/tripal/tripal/blob/7.x-3.x/tripal/includes/tripal.upload.inc).
 - Added `images/ajax-loader.gif`.

## Testing

 - To test this PR, simply create a form with the `html5_file` element type and ensure that everything is working as expected.
 - To make things easier and potentially save people time, I have a separate branch which has exactly the same code as this one, except that I have added the routing information and a class implementation for a test form.
    - The test form branch can be found [here](https://github.com/par12005/t4d8/tree/html5_file_test_form)
    - After checking out the test form branch and clearing your cache, you can find the test form at `<your site>/html5`.

### CODE REVIEW

**Review by laceysanderson — COMMENTED** [review]
## Functional Review

✅ This form element works perfectly with files < 8.39MB. I confirmed by uploading a file and then comparing the result in `sites/default/files/users/1/` with the original to confirm it was complete and not corrupt.
❌ However, regardless of what my admin settings are, I cannot upload a file > 8.39MB. When I try, I see this error:
Screen Shot 2020-04-06 at 4 49 03 PM
The error does not change regardless of what my Tripal settings are. Though the exact number is related to my php `upload_max_filesize = 10M` setting. Here are my current Tripal settings for completeness:
Screen Shot 2020-04-06 at 4 49 38 PM

**Comment by par12005** [comment]
@laceysanderson, nice catch! I think I have fixed the problem.

The function I was using to determine maximum file size was `\Drupal\Component\Utility\Environment::getUploadMaxSize()`, and I originally thought that this would directly reflect the `upload_max_filesize` value set in the `php.ini` file. However, as you pointed out, and upon further testing, even when my `upload_max_filesize` is set to `20M`, I am getting the same error in which the `getUploadMaxSize()` function is returning `8.39M`.

This is because the `getUploadMaxSize()` function returns the lesser of the two settings `upload_max_filesize` and `post_max_size`! Since we break our files into chunks when we upload them, we just need to make sure that each chunk is smaller than `post_max_size`, and that the entire file is smaller than `upload_max_filesize`. I have now switched to checking both the `upload_max_filesize` against the file size and `post_max_size` against the chunk size separately.

Furthermore, I have changed the messages for file size errors to be less confusing. The Tripal settings at `admin/tripal/files/quota` are meant for changing the maximum restrictions for the **sum** of all files created by the user, not the individual files. The error messages should now reflect the correct places to make changes to file upload configurations:

 - For a file that would exceed the user quota, this can be changed at `admin/tripal/files/quota`.
 - For a file that would exceed the maximum file upload size, this can be changed with the `upload_max_filesize` value in your `php.ini`.
 - For a file chunk that would exceed the maximum post size, this can be changed with the `post_max_size` value in your `php.ini`.

I also changed the file chunk upload requests to use POST instead of PUT. Based on what I have read, this seems to be the way that Drupal 8 wants people to be doing things, but I can change that back if you would prefer.

**Review by laceysanderson — COMMENTED** [review]
The file check changes fixed my original problem 👍 

However, the **switch to POST seems to have broken the upload**? This is what I'm experiencing:

1. Browse for the file ✔️ 
2. Click the upload button and watch the upload progress count up to the full file size ✔️ 
3. Check the `sites/default/files/tripal/users/1` directory for the file -it's not there ❌ 
4. Click the submit button and receive the following error. File is still not in `sites/default/files/tripal/users/1` ❌ 
Screen Shot 2020-04-11 at 1 55 33 PM

**Comment by par12005** [comment]
@laceysanderson, did you try rebuilding your cache? I just tried a couple files of varying size and they seem to be uploaded correctly -- They appear both in `sites/default/files/tripal/users/1` and in the `file_managed` table in the db.

**Review by laceysanderson — APPROVED** [review]
Hmmm... I could have sworn I cleared my cache earlier but I just did again 3X and now it works with the same file that did not before 🤷‍♀️ 

All my other tests worked 👍 Thanks for the contribution!

**Comment by par12005** [comment]
Yay! Thank you @laceysanderson!

**Pull request merged**
