### PR TITLE
Tripal console

### PR DESCRIPTION
**Pull request by laceysanderson**
Provide Developer friendly commands for Tripal development. This first iteration contains the command for generating a chado field type.

### CODE REVIEW

**Comment by spficklin** [comment]
Hey @laceysanderson I can review this but I've not used Drupal console before. Can you give some pointers?

**Comment by laceysanderson** [comment]
Sorry, I was not expecting a review but I'm excited that you would like to try it! Here is more information:

Prerequisites:
1. Install Drupal Console in your drupal site: https://drupalconsole.com/docs/en/getting/project
2. Enable Tripal Console to make the command available.

How to use the command:
A) Let it ask you for input! Just run `drupal tripal:generate:fieldType`. This can be run from any directory since it asks you the module you want to create the fieldType in.
```
drupal tripal:generate:fieldType

 The machine name of the module to generate the content in.:
 > tripal_chado
 The short name for the vocabulary (e.g. shcema, SO, GO, PATO, etc.).:
 > SO
 The full name of the vocabulary.:
 > 0000704
```
B) You can use `drupal tripal:generate:fieldType --help` to find out what options are available. You can provide any combination of options on the command-line and if you missed any required ones it will just prompt for them :-)
```
drupal tripal:generate:fieldType --help
Usage:
  tripal:generate:fieldType [options]
  trpgen-fieldType

Options:
      --module=MODULE                        The machine name of the module to generate the content in.
      --default-widget=DEFAULT-WIDGET        The machine name of the default widget for this field type. (e.g. obi__organism_default_widget)
      --default-formatter=DEFAULT-FORMATTER  The machine name of the default formatter for this field type. (e.g. obi__organism_default_formatter)
      --vocab-short=VOCAB-SHORT              The short name for the vocabulary (e.g. shcema, SO, GO, PATO, etc.).
      --vocab-name=VOCAB-NAME                The full name of the vocabulary.
      --vocab-description=VOCAB-DESCRIPTION  The description of the vocabulary.
      --term-name=TERM-NAME                  The name of the term.
      --term-accession=TERM-ACCESSION        The unique ID (i.e. accession) of the term.
      --term-definition=TERM-DEFINITION      The definition of the term.
      --chado-table=CHADO-TABLE              The table in Chado that the field maps to.
      --chado-column=CHADO-COLUMN            The column of the table in Chado where the value comes from.
      --chado-base=CHADO-BASE                The base table.
      --type-class[=TYPE-CLASS]              The class name for the field type (e.g. OBIOrganismItem)
      --type-label[=TYPE-LABEL]              The label for the field type (e.g. Organism)
      --type-plugin-id[=TYPE-PLUGIN-ID]      The machine name for the field type (e.g. obi__organism)
      --type-description[=TYPE-DESCRIPTION]  A short description of the type for administrators (e.g. the term description)

Help:
 Generate Tripal 4 Field Type file following coding standards
```

In both cases, once all the required options are provided it will create the files needed from the templates I provided.
Screen Shot 2020-10-30 at 11 06 40 AM

**Comment by laceysanderson** [comment]
Hi @spficklin I'm going to merge this. If you still want to try it out, please do! I've added these instructions to the docs!

**Comment by spficklin** [comment]
oh! I'm sorry. I forgot to review this.

**Pull request merged**
