### PR TITLE
Refactor Interface to Interfaces

### LINKED ISSUE #178: Interface is a reserved word
https://github.com/tripal/t4d8/blob/8d8fd93aee418c320d626c5efc273625718c2369/tripal/src/TripalVocabTerms/TripalVocabularyBase.php#L6

The preceding line violates PHP's rule about using reserved words, in this case Interface, in namespaces.
We will have to change the directory name and any references to files in that directory. Suggested by the Stackoverflow answer below, we can simply pluralize Interface to Interfaces to get around this rule for minimal change.

Sources:
https://www.php.net/manual/en/reserved.keywords.php
https://stackoverflow.com/a/44225572

### PR DESCRIPTION
**Pull request by Ferrisx4**
Interface is a reserved word for namespacing

Changed directory to Interfaces and changed all references to files within that directory.

### CODE REVIEW

**Comment by laceysanderson** [comment]
Should we change the Annotation > Annotations directory as well for consistency?

**Comment by Ferrisx4** [comment]
Yes, that makes sense. Thanks @laceysanderson I will add this.

**Comment by Ferrisx4** [comment]
Should this Annotation directory match the Drupal Annotation directory instead, for instance in https://github.com/tripal/t4d8/blob/8d8fd93aee418c320d626c5efc273625718c2369/tripal/src/TripalVocabTerms/Annotation/TripalIdSpace.php#L5?

**Comment by laceysanderson** [comment]
Boo. I guess it could go either way... but it feels wrong to me to have Interfaces but not Annotations -especially since there are multiple annotation files in that directory. So I say change it even though it may be considered against Drupal convention 😬

**Review by laceysanderson — APPROVED** [review]
Looks good to me :-) Feel free to merge once the tests pass!

**Pull request merged**
